'use server'

import { cookies } from 'next/headers'
import { getStudentInfo } from '../profile/action'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import exp from 'constants'

const BASE_URL = 'https://studentportal.green.edu.bd'

export async function getCourses() {
    const cookieStore = await cookies()
    const token = cookieStore.get('auth')?.value
    if (!token) {
        redirect('/login')
    }
    let courses: Course[] = []

    const student = await getStudentInfo()
    // console.log({ student })
    const coursesResponse = await fetch(
        BASE_URL + '/api/AutoAssignCourse?studentId=' + student.studentID,
        {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                cookie: token,
            },
        }
    )

    if (coursesResponse.url.includes('/Account/login')) {
        // cookieStore.delete("auth"); /// TODO: Probably a next.js bug [ Server ] Error: Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#options
        redirect('/login?message=Session expired')
    }
    try {
        courses = await coursesResponse.json()
    } catch (error) {
        console.error(error)
    }
    // if (!courses?.length) {
    //     return DUMMY_COURSES.map((c) => ({
    //         ...c,
    //         formalCode: c.formalCode + ' - Last Semester',
    //     }))
    // }
    return courses
}

export async function getIsPreAdvisingActive() {
    const cookieStore = await cookies()
    const token = cookieStore.get('auth')?.value
    if (!token) {
        redirect('/login')
    }

    const response = await fetch(BASE_URL + '/api/StudentStatus', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            cookie: token,
        },
    })

    if (response.url.includes('/Account/login')) {
        redirect('/login?message=Session expired')
    }

    try {
        const data = await response.json()
        const status = data[0]

        return status
    } catch (error) {
        console.error('Error checking pre-advising status:', error)
    }
}

export async function getSections(course: Course): Promise<Section[]> {
    const cookieStore = await cookies()
    const token = cookieStore.get('auth')?.value
    if (!token) {
        redirect('/login')
    }
    let sections: Section[] = []

    const sectionParam = new URLSearchParams({
        acaCalId: course.originalCalID.toString() ?? '',
        courseId: course.courseID.toString() ?? '',
        programId: '2',
        versionId: '1',
    })

    const sectionsResponse = await fetch(
        'https://studentportal.green.edu.bd/api/CourseSectionInfo?' +
            sectionParam.toString(),
        { method: 'POST', headers: { cookie: token } }
    )

    if (sectionsResponse.url.includes('/Account/login')) {
        // cookieStore.delete("auth"); /// TODO: Probably a next.js bug [ Server ] Error: Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#options
        redirect('/login?message=Session expired')
    }

    try {
        sections = await sectionsResponse.json()
        // console.log({ sections })
    } catch (error) {
        console.error(error)
    }

    // Generate a random number of sections between 20-40
    const numSections = Math.floor(Math.random() * (40 - 20 + 1)) + 20

    // Generate sections array based on course
    const dummySections = Array.from({ length: numSections }, (_, i) => {
        // Generate random capacity between 30-60
        const capacity = Math.floor(Math.random() * (60 - 30 + 1)) + 30
        // Generate random occupied seats between 0 and capacity
        const occupied = Math.floor(Math.random() * (capacity + 1))

        return {
            acaCal_SectionID: course.courseID * 100 + i, // Unique ID based on course
            sectionName: `D${i + 1}`,
            capacity,
            occupied,
        }
    })
    if (!sections?.length) {
        // return dummySections as Section[]
    }
    return sections
}

export async function deregisterSection(section: Section, course: Course) {
    const cookieStore = await cookies()
    const token = cookieStore.get('auth')?.value
    if (!token) {
        redirect('/login')
    }

    try {
        const removeSectionParam = new URLSearchParams({
            regWorkSheetId: course.regWorksheetId.toString(),
            sectionId: section.acaCal_SectionID.toString(),
            sectionName: section.sectionName,
            studentId: course.studentID.toString(),
            courseCode: course.formalCode,
            courseId: course.courseID.toString(),
            programId: '2',
            versionId: '1',
            url: 'https://studentportal.green.edu.bd/Student/StudentSectionSelection',
        })

        const removeSectionRes = await (
            await fetch(
                'https://studentportal.green.edu.bd/api/SectionRemove?' +
                    removeSectionParam.toString(),
                {
                    method: 'POST',
                    headers: { cookie: token },
                }
            )
        ).text()
        // Randomely return true or false
        // const removeSectionRes = Math.random() < 0.5
        // return removeSectionRes

        revalidatePath('/preregistration')
        // await new Promise((resolve) => setTimeout(resolve, 1000))
        if (removeSectionRes.includes('1')) return true
    } catch (error) {
        console.error(error)
    }

    return false
}

export async function registerSection(section: Section, course: Course) {
    const cookieStore = await cookies()
    const token = cookieStore.get('auth')?.value
    if (!token) {
        redirect('/login')
    }

    try {
        const selectSectionParam = new URLSearchParams({
            regWorkSheetId: course.regWorksheetId.toString(),
            newSectionId: section.acaCal_SectionID.toString(),
            sectionName: section.sectionName,
            studentId: course.studentID.toString(),
            courseCode: course.formalCode,
            courseId: course.courseID.toString(),
            programId: '2',
            versionId: '1',
            url: 'https://studentportal.green.edu.bd/Student/StudentSectionSelection',
        })

        const preSectionId = course.acaCal_SectionID?.toString()
        if (preSectionId) {
            selectSectionParam.append('preSectionId', preSectionId)
        }
        // console.log({ course })
        // params.append("preSectionId", "12506");

        const selectSectionRes = await (
            await fetch(
                'https://studentportal.green.edu.bd/api/SectionTake?' +
                    selectSectionParam.toString(),
                {
                    method: 'POST',
                    headers: { cookie: token },
                }
            )
        ).text()
        // Randomely return true or false
        // const selectSectionRes = Math.random() < 0.5
        // return selectSectionRes

        revalidatePath('/preregistration')
        // await new Promise((resolve) => setTimeout(resolve, 1000))
        console.log({ selectSectionRes })
        if (selectSectionRes.includes('1')) {
            if (preSectionId) {
                await deregisterSection(section, course)
            }
            return true
        }
    } catch (error) {
        console.error(error)
    }

    return false
}

export interface Section {
    acaCal_SectionID: number
    sectionName: string
    startHour1: string
    startMin1: string
    startAMPM1: number | null
    endHour1: string
    endMin1: string
    endAMPM1: number | null
    dayOne: string | null
    dayOneId: number | null
    startHour2: string
    startMin2: string
    startAMPM2: number | null
    endHour2: string
    endMin2: string
    endAMPM2: number | null
    dayTwo: string | null
    dayTwoId: number | null
    faculty_1: string | null
    faculty_2: string | null
    roomNo_1: string | null
    roomNo_2: string | null
    capacity: number
    occupied: number
}
export interface Course {
    regWorksheetId: number
    studentID: number
    originalCalID: number
    courseID: number
    versionID: number
    credits: number
    formalCode: string
    courseTitle: string
    acaCal_SectionID: number | null
    sectionName: string | null
    startHour1: string
    startMin1: string
    startAMPM1: number | null
    endHour1: string
    endMin1: string
    endAMPM1: number | null
    dayOne: string | null
    dayOneId: number | null
    startHour2: string
    startMin2: string
    startAMPM2: number | null
    endHour2: string
    endMin2: string
    endAMPM2: number | null
    dayTwo: string | null
    dayTwoId: number | null
    roomNo_1: string | null
    roomNo_2: string | null
    programID: number
    isRegistered: boolean | null
    isSectionBlock: boolean
    sectionTakeRequest: boolean
    isCompleted: boolean
}

const DUMMY_COURSES: Course[] = [
    {
        regWorksheetId: 11773086,
        studentID: 24132,
        originalCalID: 72,
        courseID: 458,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 307-CSE(181)',
        courseTitle: 'Data Communication',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773087,
        studentID: 24132,
        originalCalID: 72,
        courseID: 459,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 308-CSE(181)',
        courseTitle: 'Data Communication Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773095,
        studentID: 24132,
        originalCalID: 72,
        courseID: 467,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 315-CSE(201)',
        courseTitle: 'Artificial Intelligence',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773098,
        studentID: 24132,
        originalCalID: 72,
        courseID: 470,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 317-CSE(201)',
        courseTitle: 'Mathematical Analysis for Computer Science',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773099,
        studentID: 24132,
        originalCalID: 72,
        courseID: 472,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 319-CSE(201)',
        courseTitle: 'Digital System Design',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773100,
        studentID: 24132,
        originalCalID: 72,
        courseID: 473,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 321-CSE(181)',
        courseTitle: 'Human Computer Interaction',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773104,
        studentID: 24132,
        originalCalID: 72,
        courseID: 490,
        versionID: 1,
        credits: 2.0,
        formalCode: 'CSE 400A-CSE(201)',
        courseTitle: 'Capstone Project/Thesis',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773130,
        studentID: 24132,
        originalCalID: 72,
        courseID: 492,
        versionID: 1,
        credits: 2.0,
        formalCode: 'CSE 400B-CSE(201)',
        courseTitle: 'Capstone Project/Thesis',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773162,
        studentID: 24132,
        originalCalID: 72,
        courseID: 493,
        versionID: 1,
        credits: 2.0,
        formalCode: 'CSE 400C-CSE(201)',
        courseTitle: 'Capstone Project/Thesis',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773105,
        studentID: 24132,
        originalCalID: 72,
        courseID: 504,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 407-CSE(181)',
        courseTitle: 'Graph Theory',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773106,
        studentID: 24132,
        originalCalID: 72,
        courseID: 505,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 408-CSE(181)',
        courseTitle: 'Graph Theory Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773107,
        studentID: 24132,
        originalCalID: 72,
        courseID: 506,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 409-CSE(181)',
        courseTitle: 'Algorithm Engineering',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773108,
        studentID: 24132,
        originalCalID: 72,
        courseID: 508,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 410-CSE(181)',
        courseTitle: 'Algorithm Engineering Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773109,
        studentID: 24132,
        originalCalID: 72,
        courseID: 510,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 411-CSE(201)',
        courseTitle: 'Machine Learning',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773110,
        studentID: 24132,
        originalCalID: 72,
        courseID: 511,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 412-CSE(201)',
        courseTitle: 'Machine Learning Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773111,
        studentID: 24132,
        originalCalID: 72,
        courseID: 513,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 413-CSE(201)',
        courseTitle: 'Natural Language Processing',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773112,
        studentID: 24132,
        originalCalID: 72,
        courseID: 515,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 414-CSE(201)',
        courseTitle: 'Natural Language Processing Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773113,
        studentID: 24132,
        originalCalID: 72,
        courseID: 517,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 415-CSE(201)',
        courseTitle: 'Digital Image Processing',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773114,
        studentID: 24132,
        originalCalID: 72,
        courseID: 519,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 416-CSE(201)',
        courseTitle: 'Digital Image Processing Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773115,
        studentID: 24132,
        originalCalID: 72,
        courseID: 522,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 417-CSE(201)',
        courseTitle: 'Wireless Networks',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773116,
        studentID: 24132,
        originalCalID: 72,
        courseID: 524,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 418-CSE(201)',
        courseTitle: 'Wireless Networks Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773117,
        studentID: 24132,
        originalCalID: 72,
        courseID: 526,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 419-CSE(201)',
        courseTitle: 'Embedded Systems',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773118,
        studentID: 24132,
        originalCalID: 72,
        courseID: 528,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 420-CSE(201)',
        courseTitle: 'Embedded Systems Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773119,
        studentID: 24132,
        originalCalID: 72,
        courseID: 530,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 421-CSE(201)',
        courseTitle: 'VLSI Design',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773120,
        studentID: 24132,
        originalCalID: 72,
        courseID: 532,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 422-CSE(201)',
        courseTitle: 'VLSI Design Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773121,
        studentID: 24132,
        originalCalID: 72,
        courseID: 534,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 423-CSE(201)',
        courseTitle: 'Peripherals and Interfacing',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773122,
        studentID: 24132,
        originalCalID: 72,
        courseID: 536,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 424-CSE(201)',
        courseTitle: 'Peripherals and Interfacing Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773123,
        studentID: 24132,
        originalCalID: 72,
        courseID: 538,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 425-CSE(201)',
        courseTitle: 'Mobile Application Development',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773124,
        studentID: 24132,
        originalCalID: 72,
        courseID: 540,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 426-CSE(201)',
        courseTitle: 'Mobile Application Development Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773125,
        studentID: 24132,
        originalCalID: 72,
        courseID: 542,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 427-CSE(201)',
        courseTitle: 'Software Design Pattern',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773126,
        studentID: 24132,
        originalCalID: 72,
        courseID: 544,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 428-CSE(201)',
        courseTitle: 'Software Design Pattern Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773134,
        studentID: 24132,
        originalCalID: 72,
        courseID: 546,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 429-CSE(201)',
        courseTitle: 'Bioinformatics',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773135,
        studentID: 24132,
        originalCalID: 72,
        courseID: 548,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 430-CSE(201)',
        courseTitle: 'Bioinformatics Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773136,
        studentID: 24132,
        originalCalID: 72,
        courseID: 550,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 431-CSE(201)',
        courseTitle: 'Computational Geometry',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773137,
        studentID: 24132,
        originalCalID: 72,
        courseID: 552,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 432-CSE(201)',
        courseTitle: 'Computational Geometry Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773138,
        studentID: 24132,
        originalCalID: 72,
        courseID: 554,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 433-CSE(201)',
        courseTitle: 'Computer Graphics',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773139,
        studentID: 24132,
        originalCalID: 72,
        courseID: 556,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 434-CSE(201)',
        courseTitle: 'Computer Graphics Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773140,
        studentID: 24132,
        originalCalID: 72,
        courseID: 558,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 435-CSE(201)',
        courseTitle: 'Data Mining',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773141,
        studentID: 24132,
        originalCalID: 72,
        courseID: 560,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 436-CSE(201)',
        courseTitle: 'Data Mining Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773142,
        studentID: 24132,
        originalCalID: 72,
        courseID: 563,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 437-CSE(201)',
        courseTitle: 'Information Retrieval',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773143,
        studentID: 24132,
        originalCalID: 72,
        courseID: 566,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 438-CSE(201)',
        courseTitle: 'Information Retrieval Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773144,
        studentID: 24132,
        originalCalID: 72,
        courseID: 567,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 439-CSE(201)',
        courseTitle: 'Pattern Recognition',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773145,
        studentID: 24132,
        originalCalID: 72,
        courseID: 568,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 440-CSE(201)',
        courseTitle: 'Pattern Recognition Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773146,
        studentID: 24132,
        originalCalID: 72,
        courseID: 570,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 441-CSE(201)',
        courseTitle: 'Big Data Analytics',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773147,
        studentID: 24132,
        originalCalID: 72,
        courseID: 572,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 442-CSE(201)',
        courseTitle: 'Big Data Analytics Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773148,
        studentID: 24132,
        originalCalID: 72,
        courseID: 574,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 443-CSE(201)',
        courseTitle: 'Internet of Things',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773149,
        studentID: 24132,
        originalCalID: 72,
        courseID: 576,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 444-CSE(201)',
        courseTitle: 'Internet of Things Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773150,
        studentID: 24132,
        originalCalID: 72,
        courseID: 578,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 445-CSE(201)',
        courseTitle: 'Cloud Computing',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773151,
        studentID: 24132,
        originalCalID: 72,
        courseID: 579,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 446-CSE(201)',
        courseTitle: 'Cloud Computing Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773152,
        studentID: 24132,
        originalCalID: 72,
        courseID: 581,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 447-CSE(201)',
        courseTitle: 'Simulation and Modeling',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773153,
        studentID: 24132,
        originalCalID: 72,
        courseID: 582,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 448-CSE(201)',
        courseTitle: 'Simulation and Modeling Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773154,
        studentID: 24132,
        originalCalID: 72,
        courseID: 584,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 449-CSE(201)',
        courseTitle: 'Robotics',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773155,
        studentID: 24132,
        originalCalID: 72,
        courseID: 585,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 450-CSE(201)',
        courseTitle: 'Robotics Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773156,
        studentID: 24132,
        originalCalID: 72,
        courseID: 587,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 451-CSE(201)',
        courseTitle: 'Blockchain',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773157,
        studentID: 24132,
        originalCalID: 72,
        courseID: 588,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 452-CSE(201)',
        courseTitle: 'Blockchain Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773158,
        studentID: 24132,
        originalCalID: 72,
        courseID: 590,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 453-CSE(201)',
        courseTitle: 'Software Testing and Quality Assurance',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773159,
        studentID: 24132,
        originalCalID: 72,
        courseID: 591,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 454-CSE(201)',
        courseTitle: 'Software Testing and Quality Assurance Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773160,
        studentID: 24132,
        originalCalID: 72,
        courseID: 592,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 455-CSE(201)',
        courseTitle: 'Software Maintenance and Management',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773161,
        studentID: 24132,
        originalCalID: 72,
        courseID: 593,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 456-CSE(201)',
        courseTitle: 'Software Maintenance and Management Lab',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773163,
        studentID: 24132,
        originalCalID: 72,
        courseID: 594,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 458',
        courseTitle: 'Industrial Training',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773049,
        studentID: 24132,
        originalCalID: 72,
        courseID: 630,
        versionID: 1,
        credits: 0.0,
        formalCode: 'EAP 009',
        courseTitle: 'English for Academic Purposes',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773093,
        studentID: 24132,
        originalCalID: 72,
        courseID: 1251,
        versionID: 1,
        credits: 3.0,
        formalCode: 'GED 303-CSE(181)',
        courseTitle: 'Sociology',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773131,
        studentID: 24132,
        originalCalID: 72,
        courseID: 1262,
        versionID: 1,
        credits: 3.0,
        formalCode: 'GED 403-CSE(201)',
        courseTitle: 'Business Communication',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773132,
        studentID: 24132,
        originalCalID: 72,
        courseID: 1265,
        versionID: 1,
        credits: 3.0,
        formalCode: 'GED 405-CSE(201)',
        courseTitle: 'Industrial and Operational Management',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773133,
        studentID: 24132,
        originalCalID: 72,
        courseID: 1268,
        versionID: 1,
        credits: 3.0,
        formalCode: 'GED 407-CSE(201)',
        courseTitle: 'Technology Entrepreneurship',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773128,
        studentID: 24132,
        originalCalID: 72,
        courseID: 1269,
        versionID: 1,
        credits: 2.0,
        formalCode: 'GED 409',
        courseTitle: 'Professional Ethics and Environmental Protection',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773129,
        studentID: 24132,
        originalCalID: 72,
        courseID: 1270,
        versionID: 1,
        credits: 2.0,
        formalCode: 'GED 411',
        courseTitle: 'Bangladesh Studies',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773164,
        studentID: 24132,
        originalCalID: 72,
        courseID: 2109,
        versionID: 1,
        credits: 0.0,
        formalCode: 'PSD-400',
        courseTitle: 'Professional Life Skills Development (PLSD)',
        acaCal_SectionID: null,
        sectionName: null,
        startHour1: '00',
        startMin1: '00',
        startAMPM1: null,
        endHour1: '00',
        endMin1: '00',
        endAMPM1: null,
        dayOne: null,
        dayOneId: null,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773127,
        studentID: 24132,
        originalCalID: 72,
        courseID: 1259,
        versionID: 1,
        credits: 3.0,
        formalCode: 'GED 401-CSE(201)',
        courseTitle: 'Financial and Managerial Accounting',
        acaCal_SectionID: 14039,
        sectionName: '221_D3',
        startHour1: '08',
        startMin1: '30',
        startAMPM1: 1,
        endHour1: '09',
        endMin1: '45',
        endAMPM1: 1,
        dayOne: 'Mon',
        dayOneId: 3,
        startHour2: '08',
        startMin2: '30',
        startAMPM2: 1,
        endHour2: '09',
        endMin2: '45',
        endAMPM2: 1,
        dayTwo: 'Wed',
        dayTwoId: 5,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773101,
        studentID: 24132,
        originalCalID: 72,
        courseID: 474,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 323',
        courseTitle: 'Computer and Cyber Security',
        acaCal_SectionID: 14180,
        sectionName: '221_D9',
        startHour1: '09',
        startMin1: '45',
        startAMPM1: 1,
        endHour1: '11',
        endMin1: '00',
        endAMPM1: 1,
        dayOne: 'Mon',
        dayOneId: 3,
        startHour2: '09',
        startMin2: '45',
        startAMPM2: 1,
        endHour2: '11',
        endMin2: '00',
        endAMPM2: 1,
        dayTwo: 'Wed',
        dayTwoId: 5,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773090,
        studentID: 24132,
        originalCalID: 72,
        courseID: 462,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 311-CSE(181)',
        courseTitle: 'Computer Networking',
        acaCal_SectionID: 14412,
        sectionName: '221_D11',
        startHour1: '08',
        startMin1: '30',
        startAMPM1: 1,
        endHour1: '09',
        endMin1: '45',
        endAMPM1: 1,
        dayOne: 'Tue',
        dayOneId: 4,
        startHour2: '08',
        startMin2: '30',
        startAMPM2: 1,
        endHour2: '09',
        endMin2: '45',
        endAMPM2: 1,
        dayTwo: 'Thu',
        dayTwoId: 6,
        roomNo_1: 'K106-K106',
        roomNo_2: 'K106-K106',
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773091,
        studentID: 24132,
        originalCalID: 72,
        courseID: 463,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 312-CSE(181)',
        courseTitle: 'Computer Networking Lab',
        acaCal_SectionID: 14493,
        sectionName: '221_D19',
        startHour1: '11',
        startMin1: '00',
        startAMPM1: 1,
        endHour1: '01',
        endMin1: '30',
        endAMPM1: 2,
        dayOne: 'Tue',
        dayOneId: 4,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: 0,
        roomNo_1: 'K110-K110',
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773097,
        studentID: 24132,
        originalCalID: 72,
        courseID: 476,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 324-CSE(201)',
        courseTitle: 'Integrated Design Project I',
        acaCal_SectionID: 14682,
        sectionName: '221_D10',
        startHour1: '11',
        startMin1: '30',
        startAMPM1: 1,
        endHour1: '01',
        endMin1: '30',
        endAMPM1: 2,
        dayOne: 'Wed',
        dayOneId: 5,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: 0,
        roomNo_1: 'G-101-G-101',
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773096,
        studentID: 24132,
        originalCalID: 72,
        courseID: 468,
        versionID: 1,
        credits: 1.5,
        formalCode: 'CSE 316-CSE(201)',
        courseTitle: 'Artificial Intelligence Lab',
        acaCal_SectionID: 14826,
        sectionName: '213_D2',
        startHour1: '11',
        startMin1: '45',
        startAMPM1: 1,
        endHour1: '01',
        endMin1: '00',
        endAMPM1: 2,
        dayOne: 'Fri',
        dayOneId: 7,
        startHour2: '12',
        startMin2: '15',
        startAMPM2: 2,
        endHour2: '01',
        endMin2: '30',
        endAMPM2: 2,
        dayTwo: 'Sat',
        dayTwoId: 1,
        roomNo_1: 'K104-K104',
        roomNo_2: 'K104-K104',
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773102,
        studentID: 24132,
        originalCalID: 72,
        courseID: 498,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 403-CSE(201)',
        courseTitle: 'Information System and Design',
        acaCal_SectionID: 14826,
        sectionName: '213_D2',
        startHour1: '11',
        startMin1: '45',
        startAMPM1: 1,
        endHour1: '01',
        endMin1: '00',
        endAMPM1: 2,
        dayOne: 'Fri',
        dayOneId: 7,
        startHour2: '12',
        startMin2: '15',
        startAMPM2: 2,
        endHour2: '01',
        endMin2: '30',
        endAMPM2: 2,
        dayTwo: 'Sat',
        dayTwoId: 1,
        roomNo_1: 'K104-K104',
        roomNo_2: 'K104-K104',
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773082,
        studentID: 24132,
        originalCalID: 72,
        courseID: 454,
        versionID: 1,
        credits: 3.0,
        formalCode: 'CSE 303-CSE(181)',
        courseTitle: 'Microprocessors & Microcontrollers',
        acaCal_SectionID: 14884,
        sectionName: '222_D5',
        startHour1: '03',
        startMin1: '15',
        startAMPM1: 2,
        endHour1: '04',
        endMin1: '30',
        endAMPM1: 2,
        dayOne: 'Mon',
        dayOneId: 3,
        startHour2: '03',
        startMin2: '15',
        startAMPM2: 2,
        endHour2: '04',
        endMin2: '30',
        endAMPM2: 2,
        dayTwo: 'Tue',
        dayTwoId: 4,
        roomNo_1: null,
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: true,
        isCompleted: false,
    },
    {
        regWorksheetId: 11773083,
        studentID: 24132,
        originalCalID: 72,
        courseID: 455,
        versionID: 1,
        credits: 1.0,
        formalCode: 'CSE 304-CSE(181)',
        courseTitle: 'Microprocessors & Microcontrollers Lab',
        acaCal_SectionID: 14894,
        sectionName: '222_D5',
        startHour1: '11',
        startMin1: '00',
        startAMPM1: 1,
        endHour1: '12',
        endMin1: '40',
        endAMPM1: 2,
        dayOne: 'Mon',
        dayOneId: 3,
        startHour2: '00',
        startMin2: '00',
        startAMPM2: null,
        endHour2: '00',
        endMin2: '00',
        endAMPM2: null,
        dayTwo: null,
        dayTwoId: null,
        roomNo_1: 'K-109-K-109',
        roomNo_2: null,
        programID: 2,
        isRegistered: null,
        isSectionBlock: false,
        sectionTakeRequest: false,
        isCompleted: false,
    },
]
